title: Shubham S Pandit
description: linkedin: https://www.linkedin.com/in/shubham-pandit-04887822b/
description: github: https://github.com/Shubhampandit1602
description: phone: "+91 9326844808"
description: email: shubham.pandit1901@gmail.com
theme: jekyll-theme-minimal

