title: Shubham S Pandit
# logo:
# description:
# show_downloads: true
theme: jekyll-theme-minimal

# Contact Information
linkedin: https://www.linkedin.com/in/shubham-pandit-04887822b/
github: https://github.com/Shubhampandit1602
phone: "+91 9326844808"
email: shubham.pandit1901@gmail.com
